language: java
env:
  global:
  - SONATYPE_USERNAME=vpro
  - secure: jf8QjbfvYiLdqnj8c5Uj7PaZw4IQ+unuMc6iAoifejM3W2xgiEsgKkOxLr6aZ6/Y6wRt6FIBb76zZTIl9UpCQZuAlbkp7TXxGYIeGrhvMYADJalnbOnkjpQv6VovnyWSjHDjhP7F6NWYZSRiPcrNsCmTZPNLO/8prMscz4efOlEFx/KDYnUXDyqcb3sgkt89A55pCGoF07WV9vM1iYuqvE/xnya0+29B2YK/woQRotfauFFexQQCx/FioXo7mAp3lJ96QqR+SfAL646N3ekMmdUUzGGKIc2nYaGuTDQbCSfZz0+qbMlvOQCJZFxbaoJu4RRs6O3iscVcIj3DN5+AifhipitqnailphhMnNBLDpv9pQ8LHqdVhpbq8mA9W8LRWC7ROjKABHO0hu89Wyalqe8SBy4g12pHYQOVvaCssP8v4BzwD56YOhR3lFublGUTp4A52RnFIO1cnG4qUFPj10iAH0+5MLHx+d63ZugskQXXhgsz8NfeKw6IxQFTXRX/GC31/6YdVS47LtLUomLLnoissAKD7SiPzWBtRsXSUshZ0Ptqfsol2X+6eBryl+SGWZ5P9i7cpHsIyXC1mi2RkgqMYIT55LekoH7YZCGpVy4OGbgdB53ouCoD3VZ/ojBnUrMMYHngWmZAksPY7jLluIvsMPd1XzRlcqEq7RtVvd4=
jdk:
- openjdk8
sudo: false
script: mvn --fail-never -T 1C -DskipLocalStaging=true -Pdeploy test deploy
  --settings .travis-settings.xml -Dgpg.skip=true
after_success:
- bash <(curl -s https://codecov.io/bash)
